
name: Terraform Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: Pipeline-Agent

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan